apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnetserve
spec:
  selector:
    matchLabels:
      app: dotnetserve
  replicas: 1
  template:
    metadata:
      labels:
        app: dotnetserve
    spec:
      containers:
      - name: dotnetserve
        image: docker.io/mleybourne/dotnetserve:latest
        ports:
        - containerPort: 5000